name: harmony # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A musical keybord app with a pleasing design # 79 char long summary
description: |
  A beutifull keyboard app made with flutter.
  Built with love by lasheen.dev

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
apps:
  harmony:
    command: keyboard
    extensions: [flutter-stable] # Where "master" defines which Flutter channel to use for the build
parts:
  harmony:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
